# Generated by Django 6.0.4 on 2026-04-29 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва відділення')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис відділення')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ Лікаря')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Стаж роботи (років)')),
                ('bio', models.TextField(verbose_name='Коротка біографія')),
                ('photo_url', models.URLField(blank=True, verbose_name='Посилання на фото')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.category')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для запису')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='medical_records.category')),
            ],
        ),
    ]
